site_name: FRCCode.org
site_url: https://frccode.github.io
repo_url: https://github.com/frccode/frccode
repo_name: frccode/frccode
theme:
    name: material
    palette:
        primary: 'blue'
        accent: 'cyan'
    features:
        - navigation.tabs
        - navigation.top
        - navigation.sections
        - navigation.expand
        - navigation.tracking
markdown_extensions:
    - abbr
    - attr_list
    - md_in_html
    - def_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.snippets:
          auto_append:
              - includes/abbreviations.md
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.emoji:
    - footnotes
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: your-team
        repo: frccode
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.2/codemirror.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.2/theme/material.min.css
  - css/pid-simulator.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.2/codemirror.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.2/mode/clike/clike.min.js
  - js/pid-simulator.js



plugins:
#  - social:
#      enabled: true               # turns it on
#      debug_on_build: false       # replaces `debug`
#      cards_layout_options:
#        layout_dir: layouts       # replaces cards_layout_dir
#        variant: default_page     # replaces cards_layout
  # - glightbox:                  # not recognized in ci --ajs 2025-06-18
  #     background: none
  #     width: 90%
  #     shadow: true
  - search
  - include-markdown
  - group: # These plugins only run when the site is deployed
      enabled: !ENV CI
      plugins:
      - git-revision-date-localized:
          enable_creation_date: true
      #- optimize
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - meta
#        - social:
#            cards_layout_dir: layouts
#            cards_layout: default_page
#            debug: false
  - search
  - minify:
      minify_html: true
extra:
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.